### ISSUE TITLE
How to run evaluation on train.py and where is the picture of matrix stored

### ISSUE THREAD

**Issue by zhuchangyi** [AmrElsersy/Emotions-Recognition#2]

**Comment by AmrElsersy** [comment]
Sorry for late reply

The FER2013 dataset has a difficult cases / face orienations to detect, so the model hasn't a great result on its evaluation but it works really well on real demo when your face is pointing twoards the camea.

For evaluation you can run $ python3 train.py --evaluate
and it will show up the matrix picture for you (it is not saved)

**Comment by zhuchangyi** [comment]
Thank you so much.
